const Solution = () => {

	return (
		<>
			<h1>What is the solution?</h1>
			<p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nullam at mollis enim, a accumsan justo. Nulla ac hendrerit leo. Nulla pretium felis nec varius fringilla. Interdum et malesuada fames ac ante ipsum primis in faucibus. Nullam eget ex ut ipsum viverra blandit. Mauris ullamcorper quam vitae dolor ultricies mattis. In consequat tellus dapibus bibendum porttitor. Ut dictum mi vel suscipit accumsan. Cras euismod ornare venenatis. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia curae;</p>
			<p>Nulla mi velit, aliquam vitae faucibus quis, scelerisque quis ligula. Aliquam non urna a mi iaculis interdum et at nulla. Praesent vehicula congue dolor, id posuere est. Nunc tristique nulla eget ex interdum dignissim. Nullam lectus augue, consequat in sapien at, malesuada tempor lacus. Vivamus maximus elit enim, vitae imperdiet turpis elementum vel. Donec id dignissim erat. Aenean vestibulum purus et odio rhoncus, ut pellentesque massa aliquet. Aliquam vestibulum cursus erat, a posuere tortor faucibus quis.</p>
			<p>Suspendisse et turpis sapien. Cras iaculis luctus fringilla. Ut dui lacus, consequat non nisi et, cursus mattis elit. Duis dictum sit amet lacus ut porta. Nunc quis nibh nunc. Vivamus non lacus ante. Maecenas sollicitudin tincidunt ligula, in blandit nisl scelerisque quis. Suspendisse et risus a mi ullamcorper rutrum. Nunc eget velit velit. Donec nibh urna, vestibulum in urna nec, tempor maximus tortor. Nulla facilisi. Curabitur tincidunt nibh ipsum, ut congue sem ornare et.</p>
			<p>Suspendisse venenatis odio turpis, vitae iaculis enim commodo vitae. Integer luctus lorem vitae leo fringilla consectetur. Donec fermentum, augue id tempor fringilla, ipsum elit sagittis erat, non congue odio quam vitae quam. Nam mattis varius magna, vel ultricies nulla hendrerit sed. Donec cursus imperdiet nisi vel eleifend. Pellentesque felis sapien, blandit sit amet condimentum ut, iaculis et ante. Fusce dapibus bibendum nisi, nec ornare enim ultrices at. Nam ac ex laoreet, tristique turpis in, lacinia tellus. Curabitur laoreet leo a semper iaculis. Duis faucibus felis lectus, non aliquam nisl vulputate id. Duis purus metus, fermentum a blandit vel, laoreet quis ligula. Sed accumsan mi ut lacinia vehicula. Phasellus pretium tempus urna eget sollicitudin. Praesent aliquam, eros sit amet suscipit aliquet, lacus dui luctus quam, nec vehicula libero ligula a neque.</p>
			<p>In id tempor metus, vel sagittis quam. Sed lobortis lacus tempor, rutrum lacus vitae, interdum justo. Duis molestie libero lectus, vel facilisis massa hendrerit ultricies. Sed lacinia dolor a nisi vulputate vehicula. Praesent efficitur ornare nulla. Donec tristique, nibh a tincidunt vehicula, metus risus aliquam nisi, quis euismod nibh ante eu metus. Aenean accumsan lacus mattis, gravida purus quis, fermentum est. In hac habitasse platea dictumst. Etiam nibh dolor, pharetra vel enim a, rutrum dignissim tellus. Maecenas eget luctus urna, quis molestie leo.</p>
		</>
	)
};

export default Solution;
